/**
 * Differential test: worker/nlp.mjs against app/nlp.py.
 *
 * The Worker's retrieval layer is a port, so it is checked against the Python
 * it came from rather than against expectations written by hand. Fixtures in
 * test/nlp-fixtures.json are generated by scripts/export-nlp-fixtures.py, over
 * the real eighteen-car corpus.
 *
 * Scores are compared to 1e-12 rather than exactly: both sides do the same
 * arithmetic in the same order, but IEEE-754 summation over a Map and over a
 * dict need not associate identically, and a bit-level match is not what
 * matters — the ordering and the reported percentages are.
 */

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

import { TfidfIndex, surfaceForms, tokenize } from '../worker/nlp.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const fixtures = JSON.parse(readFileSync(resolve(here, 'nlp-fixtures.json'), 'utf8'));

const index = new TfidfIndex(fixtures.corpus);

test('tokenize matches the Python, bigrams included', () => {
  for (const [phrase, expected] of Object.entries(fixtures.tokenize)) {
    assert.deepEqual(tokenize(phrase), expected, `tokenize(${JSON.stringify(phrase)})`);
  }
});

test('tokenize matches the Python with bigrams off', () => {
  for (const [phrase, expected] of Object.entries(fixtures.tokenize_no_bigrams)) {
    assert.deepEqual(tokenize(phrase, { bigrams: false }), expected, phrase);
  }
});

test('surfaceForms matches the Python', () => {
  for (const [phrase, expected] of Object.entries(fixtures.surface_forms)) {
    assert.deepEqual(surfaceForms(phrase), expected, phrase);
  }
});

test('smoothed IDF matches the Python', () => {
  for (const [term, expected] of Object.entries(fixtures.idf_sample)) {
    const actual = index.idf.get(term);
    assert.ok(actual !== undefined, `term missing from index: ${term}`);
    assert.ok(
      Math.abs(actual - expected) < 1e-12,
      `idf[${term}]: ${actual} !== ${expected}`
    );
  }
});

test('search returns the same ranking and scores as the Python', () => {
  for (const [phrase, expected] of Object.entries(fixtures.search)) {
    const actual = index.search(phrase, 5);
    assert.equal(actual.length, expected.length, phrase);

    assert.deepEqual(
      actual.map(([slug]) => slug),
      expected.map(([slug]) => slug),
      `ranking for ${JSON.stringify(phrase)}`
    );
    for (const [i, [, score]] of actual.entries()) {
      assert.ok(
        Math.abs(score - expected[i][1]) < 1e-12,
        `score ${i} for ${JSON.stringify(phrase)}: ${score} !== ${expected[i][1]}`
      );
    }
  }
});

test('topTerms matches the Python', () => {
  const firstDoc = Object.keys(fixtures.corpus)[0];
  for (const [phrase, expected] of Object.entries(fixtures.top_terms)) {
    const actual = index.topTerms(
      index.vectoriseQuery(phrase),
      firstDoc,
      3,
      surfaceForms(phrase)
    );
    assert.deepEqual(actual, expected, phrase);
  }
});

test('an empty query scores nothing rather than throwing', () => {
  const vector = index.vectoriseQuery('');
  assert.equal(vector.size, 0);
  assert.equal(index.similarity(vector, Object.keys(fixtures.corpus)[0]), 0);
});

test('an unknown document id scores zero', () => {
  assert.equal(index.similarity(index.vectoriseQuery('fast'), 'no-such-car'), 0);
});
