-- Velocity Drive — schema for Neon Postgres.
--
-- Translated from the SQLite schema in app/database.py, which the Flask app
-- still uses locally. Column names and types are kept as close as Postgres
-- allows so the ported SQL in worker/ reads the same as the Python it came
-- from:
--
--   INTEGER PRIMARY KEY AUTOINCREMENT  ->  integer GENERATED BY DEFAULT AS IDENTITY
--   REAL                               ->  double precision
--   datetime('now')                    ->  now()
--   is_active INTEGER DEFAULT 1        ->  kept as integer, not boolean, because
--                                          the queries filter on `is_active = 1`
--   features TEXT DEFAULT '[]'         ->  kept as text holding JSON, not jsonb,
--                                          so both runtimes parse it the same way
--
-- Apply with:  npm run db:migrate

CREATE TABLE IF NOT EXISTS cars (
    id                integer          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug              text             NOT NULL UNIQUE,
    make              text             NOT NULL,
    model             text             NOT NULL,
    year              integer          NOT NULL,
    category          text             NOT NULL,
    body_style        text             NOT NULL,
    transmission      text             NOT NULL,
    fuel_type         text             NOT NULL,
    seats             integer          NOT NULL,
    doors             integer          NOT NULL,
    luggage           integer          NOT NULL,
    horsepower        integer          NOT NULL,
    zero_to_hundred   double precision NOT NULL,
    daily_rate        double precision NOT NULL,
    deposit           double precision NOT NULL,
    rating            double precision NOT NULL DEFAULT 4.5,
    rental_count      integer          NOT NULL DEFAULT 0,
    total_units       integer          NOT NULL DEFAULT 1,
    color             text             NOT NULL,
    accent_hex        text             NOT NULL DEFAULT '#c9a227',
    art_style         text             NOT NULL DEFAULT 'sedan',
    features          text             NOT NULL DEFAULT '[]',
    tagline           text             NOT NULL DEFAULT '',
    description       text             NOT NULL DEFAULT '',
    is_active         integer          NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS customers (
    id         integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name  text        NOT NULL,
    email      text        NOT NULL,
    phone      text        NOT NULL,
    licence_no text        NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bookings (
    id            integer          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference     text             NOT NULL UNIQUE,
    car_id        integer          NOT NULL REFERENCES cars (id) ON DELETE RESTRICT,
    customer_id   integer          NOT NULL REFERENCES customers (id) ON DELETE RESTRICT,
    pickup_date   date             NOT NULL,
    return_date   date             NOT NULL,
    pickup_branch text             NOT NULL DEFAULT 'Dubai Marina',
    days          integer          NOT NULL,
    base_total    double precision NOT NULL,
    discount      double precision NOT NULL DEFAULT 0,
    extras_total  double precision NOT NULL DEFAULT 0,
    vat           double precision NOT NULL DEFAULT 0,
    total         double precision NOT NULL,
    extras        text             NOT NULL DEFAULT '[]',
    status        text             NOT NULL DEFAULT 'confirmed',
    created_at    timestamptz      NOT NULL DEFAULT now(),
    -- A return on the pickup day is a one-day rental; earlier is nonsense.
    CONSTRAINT bookings_dates_ordered CHECK (return_date >= pickup_date)
);

-- The availability check counts overlapping bookings per car and date window.
CREATE INDEX IF NOT EXISTS idx_bookings_car_dates
    ON bookings (car_id, pickup_date, return_date);
CREATE INDEX IF NOT EXISTS idx_cars_category ON cars (category);
CREATE INDEX IF NOT EXISTS idx_bookings_reference ON bookings (reference);

CREATE TABLE IF NOT EXISTS search_events (
    id         integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query      text        NOT NULL,
    payload    text        NOT NULL DEFAULT '{}',
    top_slug   text        NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now()
);
