-- Velocity Drive fleet — GENERATED FILE, do not edit by hand.
--
-- Regenerate with:  python scripts/export-fleet.py > db/seed.sql
--
-- Emitted from app/seed.py's FLEET so the Worker and the Flask app
-- describe the same eighteen cars. ON CONFLICT DO NOTHING mirrors the
-- INSERT OR IGNORE in seed_fleet(), making re-runs a no-op.

INSERT INTO cars (slug, make, model, year, category, body_style, transmission, fuel_type, seats, doors, luggage, horsepower, zero_to_hundred, daily_rate, deposit, rating, rental_count, total_units, color, accent_hex, art_style, features, tagline, description) VALUES
    ('lamborghini-huracan-evo', 'Lamborghini', 'Huracan EVO', 2024, 'Supercar', 'Coupe', 'Automatic', 'Petrol', 2, 2, 1, 640, 2.9, 3200, 5000, 4.9, 184, 2, 'Arancio Borealis', '#ff7a18', 'supercar', '["Launch Control", "Carbon Ceramic Brakes", "Apple CarPlay", "Sport Exhaust", "Lifting System", "Alcantara Interior"]', 'The loudest way to arrive anywhere.', 'A naturally aspirated V10 supercar built for weekend drives down Jumeirah Beach Road and photo stops at the Burj Al Arab. Extreme performance, exotic styling, razor sharp handling and a soundtrack that turns heads. Ideal for special occasions, birthdays, luxury photoshoots, content creation and anyone who wants a fast flashy exotic sports car experience rather than practical transport.'),
    ('ferrari-portofino-m', 'Ferrari', 'Portofino M', 2023, 'Supercar', 'Convertible', 'Automatic', 'Petrol', 4, 2, 2, 620, 3.45, 2950, 5000, 4.8, 141, 1, 'Rosso Corsa', '#e01e2b', 'convertible', '["Retractable Hardtop", "Magnaride Suspension", "Bluetooth", "Heated Seats", "Reversing Camera", "Carbon Fibre Trim"]', 'Drop the roof, keep the drama.', 'A convertible grand tourer that folds its hardtop in fourteen seconds. Fast and glamorous but far more usable than a hard core supercar, with two small rear seats and real luggage space. Perfect for open top coastal cruising, romantic evenings, anniversaries and couples who want an exotic car they can actually drive comfortably for a few hours.'),
    ('rolls-royce-ghost', 'Rolls-Royce', 'Ghost', 2024, 'Luxury', 'Sedan', 'Automatic', 'Petrol', 5, 4, 3, 563, 4.8, 4100, 7500, 5.0, 96, 1, 'English White', '#d8d3c4', 'luxury-sedan', '["Starlight Headliner", "Rear Executive Seats", "Massage Seats", "Chauffeur Partition", "Bespoke Audio", "Champagne Cooler"]', 'Silence, engineered.', 'The definitive chauffeur driven limousine. Whisper quiet cabin, starlight headliner and rear seats that recline. This is the car for weddings, executive airport transfers, corporate VIP guests, red carpet arrivals and formal business events where arriving with understated prestige and total comfort matters more than outright speed.'),
    ('mercedes-s500', 'Mercedes-Benz', 'S 500 L', 2024, 'Luxury', 'Sedan', 'Automatic', 'Petrol', 5, 4, 3, 429, 4.9, 1250, 3000, 4.8, 312, 4, 'Obsidian Black', '#9aa7b4', 'luxury-sedan', '["Burmester 3D Audio", "Rear Entertainment", "Massage Seats", "Ambient Lighting", "Adaptive Cruise", "Wireless CarPlay"]', 'The executive standard.', 'The benchmark executive saloon for business travel. Long wheelbase rear legroom, massaging seats and an air suspension that erases road noise on the Sheikh Zayed Road. The sensible professional choice for corporate clients, consultants, airport pickups and multi day business trips where comfort, discretion and a quiet cabin for calls matter most.'),
    ('bmw-m4-competition', 'BMW', 'M4 Competition', 2024, 'Sports', 'Coupe', 'Automatic', 'Petrol', 4, 2, 2, 503, 3.5, 1150, 3000, 4.7, 268, 3, 'Isle of Man Green', '#1f7a4d', 'sports-coupe', '["M Sport Exhaust", "Carbon Bucket Seats", "Head Up Display", "Drift Analyser", "Harman Kardon Audio", "Apple CarPlay"]', 'Track focus, street legal.', 'A twin turbo straight six coupe that bridges daily usability and genuine performance. Quick, aggressive and engaging to drive, but with a usable boot and rear seats. A strong pick for driving enthusiasts, track day spectators and younger renters who want something fast and sporty without full supercar running costs.'),
    ('porsche-911-carrera', 'Porsche', '911 Carrera S', 2024, 'Sports', 'Coupe', 'Automatic', 'Petrol', 4, 2, 2, 443, 3.5, 1650, 4000, 4.9, 203, 2, 'GT Silver', '#b9bdc2', 'sports-coupe', '["Sport Chrono", "PASM Suspension", "Bose Audio", "Lane Keep Assist", "Wireless CarPlay", "Sport Seats Plus"]', 'The everyday exotic.', 'The sports car you can genuinely use every day. Precise steering, rear engine balance and build quality that shrugs off long distance driving. Suits renters who want serious performance and prestige but also comfort, reliability and enough practicality for a weekend away or a long desert highway road trip.'),
    ('range-rover-vogue', 'Land Rover', 'Range Rover Vogue', 2024, 'SUV', 'SUV', 'Automatic', 'Petrol', 5, 5, 4, 395, 6.0, 1450, 3500, 4.8, 287, 4, 'Santorini Black', '#3c4a5a', 'suv', '["Air Suspension", "Terrain Response", "Meridian Audio", "Panoramic Roof", "Heated Rear Seats", "360 Camera"]', 'Command every surface.', 'Commanding luxury SUV with genuine off road ability and a cabin that isolates you from everything outside. Handles desert tracks, school runs and hotel valets with equal confidence. A favourite for families, desert safari trips, golf weekends and anyone who wants a high driving position with premium comfort and space.'),
    ('toyota-land-cruiser', 'Toyota', 'Land Cruiser 300', 2024, 'SUV', 'SUV', 'Automatic', 'Petrol', 7, 5, 4, 409, 6.7, 720, 2000, 4.7, 421, 6, 'Pearl White', '#c8ccd0', 'suv', '["7 Seats", "4WD Low Range", "Roof Rails", "Cooled Seats", "Apple CarPlay", "Cruise Control"]', 'Goes anywhere, carries everyone.', 'The workhorse of the region. Seven seats, proper four wheel drive and legendary reliability in heat and sand. The default choice for large families, group trips, dune bashing, camping in Hatta and long intercity drives to Abu Dhabi or Oman where space, durability and running cost matter more than styling.'),
    ('nissan-patrol-platinum', 'Nissan', 'Patrol Platinum', 2023, 'SUV', 'SUV', 'Automatic', 'Petrol', 7, 5, 4, 400, 6.8, 650, 2000, 4.6, 388, 5, 'Gun Metallic', '#6b7280', 'suv', '["7 Seats", "4WD", "Around View Monitor", "Bose Audio", "Rear Climate Control", "Tow Package"]', 'The desert''s favourite.', 'A big comfortable V8 family SUV built for the Gulf. Cools fast in summer, seats seven adults and tows easily. Popular for extended family holidays, group airport runs, weekend desert camping and anyone needing maximum passenger and luggage capacity at a reasonable mid range daily price.'),
    ('tesla-model-3-lr', 'Tesla', 'Model 3 Long Range', 2025, 'Electric', 'Sedan', 'Automatic', 'Electric', 5, 4, 3, 394, 4.4, 420, 1500, 4.7, 502, 8, 'Deep Blue Metallic', '#2f6df6', 'ev-sedan', '["Autopilot", "629km Range", "Glass Roof", "Supercharging", "Premium Audio", "Sentry Mode"]', 'Zero fuel stops, zero fuss.', 'Quick, quiet and cheap to run with no petrol costs at all. Excellent for cost conscious renters, tech enthusiasts, environmentally minded travellers and long monthly rentals where fuel savings compound. Instant torque makes it feel fast in city traffic while Autopilot eases motorway commuting.'),
    ('tesla-model-y', 'Tesla', 'Model Y', 2025, 'Electric', 'SUV', 'Automatic', 'Electric', 5, 5, 4, 384, 5.0, 460, 1500, 4.6, 364, 6, 'Pearl White', '#5b8def', 'ev-sedan', '["Autopilot", "Huge Boot", "Glass Roof", "Supercharging", "Heat Pump", "Wireless Charging"]', 'Electric space, family sized.', 'A practical electric crossover with a cavernous boot and a high seating position. Combines low running costs with family friendly space, making it a smart pick for small families, longer stays, airport trips with lots of luggage and renters who want an electric car but need more room than a saloon.'),
    ('mercedes-v-class', 'Mercedes-Benz', 'V-Class Avantgarde', 2023, 'Van', 'MPV', 'Automatic', 'Diesel', 8, 5, 6, 237, 8.1, 890, 2500, 4.6, 156, 3, 'Cavansite Blue', '#274b8a', 'van', '["8 Seats", "Conference Seating", "Rear Climate", "Electric Sliding Doors", "Large Luggage Bay", "USB-C Ports"]', 'Move the whole team.', 'An eight seat luxury people mover with conference style seating and a huge luggage bay. Built for corporate group transfers, conference delegations, large family arrivals, wedding party transport and tour groups who need everyone plus all the suitcases in one comfortable air conditioned vehicle.'),
    ('bentley-continental-gt', 'Bentley', 'Continental GT', 2024, 'Luxury', 'Coupe', 'Automatic', 'Petrol', 4, 2, 2, 550, 4.0, 2400, 5000, 4.9, 112, 1, 'Glacier White', '#e6e2d6', 'luxury-coupe', '["Rotating Display", "Naim Audio", "Diamond Quilted Leather", "All Wheel Drive", "Massage Seats", "Night Vision"]', 'Grand touring, perfected.', 'A grand tourer that crosses continents in hand stitched comfort. Enormous effortless torque paired with a cabin of quilted leather and machined metal. Chosen for milestone celebrations, luxury road trips, elegant wedding cars and clients who want prestige and craftsmanship rather than aggressive supercar styling.'),
    ('audi-q8-quattro', 'Audi', 'Q8 55 TFSI', 2024, 'SUV', 'SUV', 'Automatic', 'Petrol', 5, 5, 4, 335, 5.9, 980, 2500, 4.7, 234, 3, 'Navarra Blue', '#1d4f91', 'suv', '["Quattro AWD", "Virtual Cockpit", "Bang & Olufsen Audio", "Adaptive Air Suspension", "Matrix LED", "360 Camera"]', 'Sharp suit, big boots.', 'A coupe styled premium SUV that mixes sporty road manners with family practicality. Quattro all wheel drive, a sharp digital cockpit and a modern understated design. Good for business travellers with luggage, small families wanting something stylish, and renters after a premium SUV that is less imposing than a full size off roader.'),
    ('ford-mustang-gt', 'Ford', 'Mustang GT', 2024, 'Sports', 'Convertible', 'Automatic', 'Petrol', 4, 2, 2, 486, 4.4, 690, 2000, 4.5, 319, 4, 'Race Red', '#cf2027', 'convertible', '["V8 Engine", "Soft Top Convertible", "Track Apps", "B&O Audio", "Launch Control", "Apple CarPlay"]', 'Affordable American muscle.', 'A V8 convertible that delivers genuine noise and drama for a fraction of supercar money. Roof down cruising along the beach, loud exhaust and classic muscle car styling. The value option for renters who want a fun exciting weekend car, a memorable birthday drive or an open top experience on a moderate budget.'),
    ('toyota-corolla-hybrid', 'Toyota', 'Corolla Hybrid', 2024, 'Economy', 'Sedan', 'Automatic', 'Hybrid', 5, 4, 2, 138, 9.2, 135, 800, 4.5, 784, 12, 'Silver Metallic', '#8e979f', 'sedan', '["Hybrid Economy", "Apple CarPlay", "Lane Assist", "Reversing Camera", "Cruise Control", "Bluetooth"]', 'Cheap to run, easy to park.', 'The sensible budget choice. Hybrid fuel economy, low daily rate and effortless city driving. Ideal for students, long stay visitors, daily commuting, ride hailing work and anyone who wants the cheapest reliable automatic car for getting around Dubai without worrying about fuel bills or parking size.'),
    ('nissan-sunny', 'Nissan', 'Sunny', 2024, 'Economy', 'Sedan', 'Automatic', 'Petrol', 5, 4, 2, 99, 11.5, 99, 700, 4.2, 912, 15, 'Brilliant Silver', '#a6adb4', 'sedan', '["Bluetooth", "Reversing Camera", "USB Charging", "Air Conditioning", "Cruise Control", "Automatic"]', 'The lowest daily rate we offer.', 'Our most affordable car. Simple, economical and perfectly adequate for getting from A to B. The best value for tight budgets, short errands, first time renters, students and long monthly hires where the priority is the cheapest possible price rather than performance, badge or luxury features.'),
    ('mini-cooper-s', 'MINI', 'Cooper S', 2024, 'Compact', 'Hatchback', 'Automatic', 'Petrol', 4, 3, 1, 201, 6.6, 310, 1200, 4.6, 298, 5, 'Chili Red', '#d6373f', 'hatchback', '["Go Kart Handling", "Harman Kardon Audio", "Panoramic Roof", "Apple CarPlay", "Sport Mode", "Ambient Lighting"]', 'Small car, big personality.', 'A fun compact hatchback with sharp go kart handling and retro styling. Easy to park in tight mall garages but genuinely entertaining on a back road. Suits couples, solo travellers, city driving and renters who want character and a bit of fun without paying sports car prices or dealing with a large vehicle.')
ON CONFLICT (slug) DO NOTHING;
